sudo: required

services:
  - docker

language: python

dist: bionic  # Required for Travis to support python version >3.9

python:
  - "3.11"

before_install:
  - pip install --upgrade pip pipenv setuptools wheel
  - pip uninstall -y numpy  # Remove the vulnerable Numpy which Travis provides

install:
  - pipenv install --dev --deploy

script:
  - make check
  - make flake
  - make vulture
  - make build

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1

branches:
  only:
    - main
