sudo: required

services:
  - docker

language: python

python:
  - "3.9"

before_install:
  - python -m pip install --upgrade pip
  - python -m pip install --upgrade setuptools
  - python -m pip install --upgrade wheel
  - pip uninstall -y numpy  # Remove the vulnerable Numpy which Travis provides
  - rm -rf venv  # Remove the venv which Travis creates containing old/vulnerable packages

install:
  - pip install -U pipenv
  - pipenv install --dev --deploy

script:
  - make package_vulnerability
  - make flake
  - make vulture
  - make build

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1

branches:
  only:
    - main
