sudo: required

services:
  - docker

language: python

dist: bionic  # Required for Travis to support python version >3.9

python:
  - "3.11"

before_install:
  - deactivate # Deactivate the virtualenv Travis dumps us in, so that we can fix out of date global dependencies
  - pyenv global 3.11 # Ensure the right global python version is being used
  - pip install --upgrade pip pipenv setuptools wheel

install:
  - pipenv install --dev --deploy

script:
  - make check
  - make flake
  - make vulture
  - make build

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1

branches:
  only:
    - main
