sudo: required

services:
  - docker

language: python

python:
  - "3.9"

before_install:
  - rm -rf venv  # Remove the venv which Travis creates containing old/vulnerable packages
  - pip install --upgrade pip pipenv setuptools wheel
  - pip uninstall -y numpy  # Remove the vulnerable Numpy which Travis provides

install:
  - pip list
  - pipenv install --dev --deploy

script:
  - make package_vulnerability
  - make flake
  - make vulture
  - make build

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1

branches:
  only:
    - main
