sudo: required

services:
  - docker

language: python

python:
  - "3.9"

before_install:
  - pip install --upgrade pip pipenv setuptools wheel
  - pip uninstall -y numpy  # Remove the vulnerable Numpy which Travis provides

install:
  - pipenv install --dev --deploy

script:
  - pipenv check -i 52495 -i 51499  # Ignore vulnerabilities in wheel and setuptools, which Travis flatly refuses to update properly (but should not be present in any properly updated environment)
  - make flake
  - make vulture
  - make build

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1

branches:
  only:
    - main
