sudo: required

services:
  - docker

language: python

python:
  - "3.9"

before_install:
  - python -m pip install --upgrade pip
  - python -m pip install --upgrade py

install:
  - pip install pipenv
  - pipenv install --dev --deploy

script:
  - make package_vulnerability
  - make flake
  - make vulture
  - make build

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1

branches:
  only:
    - main
